### ISSUE TITLE
Incorrect workspace

### ISSUE THREAD

**Issue by LunarWatcher** [ananagame/vimsence#1]
The current code, at least with Vim 8.1, appears to return the directory the file is in, and not necessarily the workspace. 

The workspace is on most cases the root of the project, and not a subfolder within that root. Typing `:pwd` in vim gets the correct result anyway. 

To demonstrate the problem: in my project, I have several subfolders. If I go into the folder for a testing program, instead of the name of the root folder, I get the name of the subfolder as the workspace on Discord.

**Comment by ananagame** [comment]
All done, thanks for the report! :)

**Comment by LunarWatcher** [comment]
Thanks! 

Unfortunately, your patch presents an issue with Windows :] `getcwd()` on Windows returns paths with backslashes instead of forward slashes (i.e. `C:\some\folder` instead of `C:/some/folder`. Never understood why, but that's aside the point). It instead displays the full path instead of just the folder name.

**Comment by ananagame** [comment]
I think that's good right now, thanks! :)
